# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChordBookUI.ui'
#
# Created: Mon Nov 18 20:55:41 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1058, 791)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1041, 751))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.gridLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1037, 747))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(10, 60, 1021, 301))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.line = QtGui.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(80, 250, 921, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(80, 210, 921, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(80, 163, 921, 31))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(80, 125, 921, 31))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.frame)
        self.line_5.setGeometry(QtCore.QRect(80, 90, 921, 21))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.frame)
        self.line_6.setGeometry(QtCore.QRect(80, 50, 921, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.lineEdit = QtGui.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(80, 20, 931, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.S6 = QtGui.QComboBox(self.frame)
        self.S6.setGeometry(QtCore.QRect(10, 250, 61, 41))
        self.S6.setObjectName(_fromUtf8("S6"))
        self.S5 = QtGui.QComboBox(self.frame)
        self.S5.setGeometry(QtCore.QRect(10, 210, 61, 41))
        self.S5.setObjectName(_fromUtf8("S5"))
        self.S4 = QtGui.QComboBox(self.frame)
        self.S4.setGeometry(QtCore.QRect(10, 170, 61, 41))
        self.S4.setObjectName(_fromUtf8("S4"))
        self.S3 = QtGui.QComboBox(self.frame)
        self.S3.setGeometry(QtCore.QRect(10, 130, 61, 41))
        self.S3.setObjectName(_fromUtf8("S3"))
        self.S2 = QtGui.QComboBox(self.frame)
        self.S2.setGeometry(QtCore.QRect(10, 90, 61, 41))
        self.S2.setObjectName(_fromUtf8("S2"))
        self.S1 = QtGui.QComboBox(self.frame)
        self.S1.setGeometry(QtCore.QRect(10, 50, 61, 41))
        self.S1.setObjectName(_fromUtf8("S1"))
        self.S6Widget = QtGui.QWidget(self.frame)
        self.S6Widget.setGeometry(QtCore.QRect(80, 240, 931, 41))
        self.S6Widget.setObjectName(_fromUtf8("S6Widget"))
        self.S6F1 = QtGui.QCheckBox(self.S6Widget)
        self.S6F1.setGeometry(QtCore.QRect(60, 10, 16, 20))
        self.S6F1.setText(_fromUtf8(""))
        self.S6F1.setAutoExclusive(True)
        self.S6F1.setObjectName(_fromUtf8("S6F1"))
        self.S6F9 = QtGui.QCheckBox(self.S6Widget)
        self.S6F9.setGeometry(QtCore.QRect(380, 10, 16, 20))
        self.S6F9.setText(_fromUtf8(""))
        self.S6F9.setAutoExclusive(True)
        self.S6F9.setObjectName(_fromUtf8("S6F9"))
        self.S6F8 = QtGui.QCheckBox(self.S6Widget)
        self.S6F8.setGeometry(QtCore.QRect(340, 10, 16, 20))
        self.S6F8.setText(_fromUtf8(""))
        self.S6F8.setAutoExclusive(True)
        self.S6F8.setObjectName(_fromUtf8("S6F8"))
        self.S6F17 = QtGui.QCheckBox(self.S6Widget)
        self.S6F17.setGeometry(QtCore.QRect(700, 10, 16, 20))
        self.S6F17.setText(_fromUtf8(""))
        self.S6F17.setAutoExclusive(True)
        self.S6F17.setObjectName(_fromUtf8("S6F17"))
        self.S6F14 = QtGui.QCheckBox(self.S6Widget)
        self.S6F14.setGeometry(QtCore.QRect(580, 10, 16, 20))
        self.S6F14.setText(_fromUtf8(""))
        self.S6F14.setAutoExclusive(True)
        self.S6F14.setObjectName(_fromUtf8("S6F14"))
        self.S6F5 = QtGui.QCheckBox(self.S6Widget)
        self.S6F5.setGeometry(QtCore.QRect(220, 10, 16, 20))
        self.S6F5.setText(_fromUtf8(""))
        self.S6F5.setAutoExclusive(True)
        self.S6F5.setObjectName(_fromUtf8("S6F5"))
        self.S6F18 = QtGui.QCheckBox(self.S6Widget)
        self.S6F18.setGeometry(QtCore.QRect(740, 10, 16, 20))
        self.S6F18.setText(_fromUtf8(""))
        self.S6F18.setAutoExclusive(True)
        self.S6F18.setObjectName(_fromUtf8("S6F18"))
        self.S6F4 = QtGui.QCheckBox(self.S6Widget)
        self.S6F4.setGeometry(QtCore.QRect(180, 10, 16, 20))
        self.S6F4.setText(_fromUtf8(""))
        self.S6F4.setAutoExclusive(True)
        self.S6F4.setObjectName(_fromUtf8("S6F4"))
        self.S6F22 = QtGui.QCheckBox(self.S6Widget)
        self.S6F22.setGeometry(QtCore.QRect(900, 10, 21, 20))
        self.S6F22.setText(_fromUtf8(""))
        self.S6F22.setAutoExclusive(True)
        self.S6F22.setObjectName(_fromUtf8("S6F22"))
        self.S6F19 = QtGui.QCheckBox(self.S6Widget)
        self.S6F19.setGeometry(QtCore.QRect(780, 10, 16, 20))
        self.S6F19.setText(_fromUtf8(""))
        self.S6F19.setAutoExclusive(True)
        self.S6F19.setObjectName(_fromUtf8("S6F19"))
        self.S6F6 = QtGui.QCheckBox(self.S6Widget)
        self.S6F6.setGeometry(QtCore.QRect(260, 10, 16, 20))
        self.S6F6.setText(_fromUtf8(""))
        self.S6F6.setAutoExclusive(True)
        self.S6F6.setObjectName(_fromUtf8("S6F6"))
        self.S6F7 = QtGui.QCheckBox(self.S6Widget)
        self.S6F7.setGeometry(QtCore.QRect(300, 10, 16, 20))
        self.S6F7.setText(_fromUtf8(""))
        self.S6F7.setAutoExclusive(True)
        self.S6F7.setObjectName(_fromUtf8("S6F7"))
        self.S6F21 = QtGui.QCheckBox(self.S6Widget)
        self.S6F21.setGeometry(QtCore.QRect(860, 10, 16, 20))
        self.S6F21.setText(_fromUtf8(""))
        self.S6F21.setAutoExclusive(True)
        self.S6F21.setObjectName(_fromUtf8("S6F21"))
        self.S6F13 = QtGui.QCheckBox(self.S6Widget)
        self.S6F13.setGeometry(QtCore.QRect(540, 10, 16, 20))
        self.S6F13.setText(_fromUtf8(""))
        self.S6F13.setAutoExclusive(True)
        self.S6F13.setObjectName(_fromUtf8("S6F13"))
        self.S6F11 = QtGui.QCheckBox(self.S6Widget)
        self.S6F11.setGeometry(QtCore.QRect(460, 10, 16, 20))
        self.S6F11.setText(_fromUtf8(""))
        self.S6F11.setAutoExclusive(True)
        self.S6F11.setObjectName(_fromUtf8("S6F11"))
        self.S6F12 = QtGui.QCheckBox(self.S6Widget)
        self.S6F12.setGeometry(QtCore.QRect(500, 10, 16, 20))
        self.S6F12.setText(_fromUtf8(""))
        self.S6F12.setAutoExclusive(True)
        self.S6F12.setObjectName(_fromUtf8("S6F12"))
        self.S6F16 = QtGui.QCheckBox(self.S6Widget)
        self.S6F16.setGeometry(QtCore.QRect(660, 10, 16, 20))
        self.S6F16.setText(_fromUtf8(""))
        self.S6F16.setAutoExclusive(True)
        self.S6F16.setObjectName(_fromUtf8("S6F16"))
        self.S6F3 = QtGui.QCheckBox(self.S6Widget)
        self.S6F3.setGeometry(QtCore.QRect(140, 10, 16, 20))
        self.S6F3.setText(_fromUtf8(""))
        self.S6F3.setAutoExclusive(True)
        self.S6F3.setObjectName(_fromUtf8("S6F3"))
        self.S6F10 = QtGui.QCheckBox(self.S6Widget)
        self.S6F10.setGeometry(QtCore.QRect(420, 10, 16, 20))
        self.S6F10.setText(_fromUtf8(""))
        self.S6F10.setAutoExclusive(True)
        self.S6F10.setObjectName(_fromUtf8("S6F10"))
        self.S6F20 = QtGui.QCheckBox(self.S6Widget)
        self.S6F20.setGeometry(QtCore.QRect(820, 10, 16, 20))
        self.S6F20.setText(_fromUtf8(""))
        self.S6F20.setAutoExclusive(True)
        self.S6F20.setObjectName(_fromUtf8("S6F20"))
        self.S6F15 = QtGui.QCheckBox(self.S6Widget)
        self.S6F15.setGeometry(QtCore.QRect(620, 10, 16, 20))
        self.S6F15.setText(_fromUtf8(""))
        self.S6F15.setAutoExclusive(True)
        self.S6F15.setObjectName(_fromUtf8("S6F15"))
        self.S6F2 = QtGui.QCheckBox(self.S6Widget)
        self.S6F2.setGeometry(QtCore.QRect(100, 10, 16, 20))
        self.S6F2.setText(_fromUtf8(""))
        self.S6F2.setAutoExclusive(True)
        self.S6F2.setObjectName(_fromUtf8("S6F2"))
        self.S6F0 = QtGui.QCheckBox(self.S6Widget)
        self.S6F0.setGeometry(QtCore.QRect(20, 10, 21, 20))
        self.S6F0.setText(_fromUtf8(""))
        self.S6F0.setChecked(True)
        self.S6F0.setAutoExclusive(True)
        self.S6F0.setObjectName(_fromUtf8("S6F0"))
        self.results = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.results.setGeometry(QtCore.QRect(10, 490, 1011, 231))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.results.setFont(font)
        self.results.setObjectName(_fromUtf8("results"))
        self.identify_chord = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.identify_chord.setGeometry(QtCore.QRect(270, 410, 541, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.identify_chord.setFont(font)
        self.identify_chord.setObjectName(_fromUtf8("identify_chord"))
        self.clear_fret_selections = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.clear_fret_selections.setGeometry(QtCore.QRect(840, 370, 181, 28))
        self.clear_fret_selections.setObjectName(_fromUtf8("clear_fret_selections"))
        self.tuning = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.tuning.setGeometry(QtCore.QRect(440, 10, 331, 41))
        self.tuning.setObjectName(_fromUtf8("tuning"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(320, 10, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.S5Widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.S5Widget.setGeometry(QtCore.QRect(90, 260, 931, 41))
        self.S5Widget.setObjectName(_fromUtf8("S5Widget"))
        self.S5F9 = QtGui.QCheckBox(self.S5Widget)
        self.S5F9.setGeometry(QtCore.QRect(380, 10, 16, 20))
        self.S5F9.setText(_fromUtf8(""))
        self.S5F9.setAutoExclusive(True)
        self.S5F9.setObjectName(_fromUtf8("S5F9"))
        self.S5F2 = QtGui.QCheckBox(self.S5Widget)
        self.S5F2.setGeometry(QtCore.QRect(100, 10, 16, 20))
        self.S5F2.setText(_fromUtf8(""))
        self.S5F2.setAutoExclusive(True)
        self.S5F2.setObjectName(_fromUtf8("S5F2"))
        self.S5F7 = QtGui.QCheckBox(self.S5Widget)
        self.S5F7.setGeometry(QtCore.QRect(300, 10, 16, 20))
        self.S5F7.setText(_fromUtf8(""))
        self.S5F7.setAutoExclusive(True)
        self.S5F7.setObjectName(_fromUtf8("S5F7"))
        self.S5F1 = QtGui.QCheckBox(self.S5Widget)
        self.S5F1.setGeometry(QtCore.QRect(60, 10, 16, 20))
        self.S5F1.setText(_fromUtf8(""))
        self.S5F1.setAutoExclusive(True)
        self.S5F1.setObjectName(_fromUtf8("S5F1"))
        self.S5F4 = QtGui.QCheckBox(self.S5Widget)
        self.S5F4.setGeometry(QtCore.QRect(180, 10, 16, 20))
        self.S5F4.setText(_fromUtf8(""))
        self.S5F4.setAutoExclusive(True)
        self.S5F4.setObjectName(_fromUtf8("S5F4"))
        self.S5F14 = QtGui.QCheckBox(self.S5Widget)
        self.S5F14.setGeometry(QtCore.QRect(580, 10, 16, 20))
        self.S5F14.setText(_fromUtf8(""))
        self.S5F14.setAutoExclusive(True)
        self.S5F14.setObjectName(_fromUtf8("S5F14"))
        self.S5F5 = QtGui.QCheckBox(self.S5Widget)
        self.S5F5.setGeometry(QtCore.QRect(220, 10, 16, 20))
        self.S5F5.setText(_fromUtf8(""))
        self.S5F5.setAutoExclusive(True)
        self.S5F5.setObjectName(_fromUtf8("S5F5"))
        self.S5F13 = QtGui.QCheckBox(self.S5Widget)
        self.S5F13.setGeometry(QtCore.QRect(540, 10, 16, 20))
        self.S5F13.setText(_fromUtf8(""))
        self.S5F13.setAutoExclusive(True)
        self.S5F13.setObjectName(_fromUtf8("S5F13"))
        self.S5F6 = QtGui.QCheckBox(self.S5Widget)
        self.S5F6.setGeometry(QtCore.QRect(260, 10, 16, 20))
        self.S5F6.setText(_fromUtf8(""))
        self.S5F6.setAutoExclusive(True)
        self.S5F6.setObjectName(_fromUtf8("S5F6"))
        self.S5F22 = QtGui.QCheckBox(self.S5Widget)
        self.S5F22.setGeometry(QtCore.QRect(900, 10, 21, 20))
        self.S5F22.setText(_fromUtf8(""))
        self.S5F22.setAutoExclusive(True)
        self.S5F22.setObjectName(_fromUtf8("S5F22"))
        self.S5F19 = QtGui.QCheckBox(self.S5Widget)
        self.S5F19.setGeometry(QtCore.QRect(780, 10, 16, 20))
        self.S5F19.setText(_fromUtf8(""))
        self.S5F19.setAutoExclusive(True)
        self.S5F19.setObjectName(_fromUtf8("S5F19"))
        self.S5F16 = QtGui.QCheckBox(self.S5Widget)
        self.S5F16.setGeometry(QtCore.QRect(660, 10, 16, 20))
        self.S5F16.setText(_fromUtf8(""))
        self.S5F16.setAutoExclusive(True)
        self.S5F16.setObjectName(_fromUtf8("S5F16"))
        self.S5F11 = QtGui.QCheckBox(self.S5Widget)
        self.S5F11.setGeometry(QtCore.QRect(460, 10, 16, 20))
        self.S5F11.setText(_fromUtf8(""))
        self.S5F11.setAutoExclusive(True)
        self.S5F11.setObjectName(_fromUtf8("S5F11"))
        self.S5F21 = QtGui.QCheckBox(self.S5Widget)
        self.S5F21.setGeometry(QtCore.QRect(860, 10, 16, 20))
        self.S5F21.setText(_fromUtf8(""))
        self.S5F21.setAutoExclusive(True)
        self.S5F21.setObjectName(_fromUtf8("S5F21"))
        self.S5F10 = QtGui.QCheckBox(self.S5Widget)
        self.S5F10.setGeometry(QtCore.QRect(420, 10, 16, 20))
        self.S5F10.setText(_fromUtf8(""))
        self.S5F10.setAutoExclusive(True)
        self.S5F10.setObjectName(_fromUtf8("S5F10"))
        self.S5F12 = QtGui.QCheckBox(self.S5Widget)
        self.S5F12.setGeometry(QtCore.QRect(500, 10, 16, 20))
        self.S5F12.setText(_fromUtf8(""))
        self.S5F12.setAutoExclusive(True)
        self.S5F12.setObjectName(_fromUtf8("S5F12"))
        self.S5F20 = QtGui.QCheckBox(self.S5Widget)
        self.S5F20.setGeometry(QtCore.QRect(820, 10, 16, 20))
        self.S5F20.setText(_fromUtf8(""))
        self.S5F20.setAutoExclusive(True)
        self.S5F20.setObjectName(_fromUtf8("S5F20"))
        self.S5F3 = QtGui.QCheckBox(self.S5Widget)
        self.S5F3.setGeometry(QtCore.QRect(140, 10, 16, 20))
        self.S5F3.setText(_fromUtf8(""))
        self.S5F3.setAutoExclusive(True)
        self.S5F3.setObjectName(_fromUtf8("S5F3"))
        self.S5F15 = QtGui.QCheckBox(self.S5Widget)
        self.S5F15.setGeometry(QtCore.QRect(620, 10, 16, 20))
        self.S5F15.setText(_fromUtf8(""))
        self.S5F15.setAutoExclusive(True)
        self.S5F15.setObjectName(_fromUtf8("S5F15"))
        self.S5F8 = QtGui.QCheckBox(self.S5Widget)
        self.S5F8.setGeometry(QtCore.QRect(340, 10, 16, 20))
        self.S5F8.setText(_fromUtf8(""))
        self.S5F8.setAutoExclusive(True)
        self.S5F8.setObjectName(_fromUtf8("S5F8"))
        self.S5F17 = QtGui.QCheckBox(self.S5Widget)
        self.S5F17.setGeometry(QtCore.QRect(700, 10, 16, 20))
        self.S5F17.setText(_fromUtf8(""))
        self.S5F17.setAutoExclusive(True)
        self.S5F17.setObjectName(_fromUtf8("S5F17"))
        self.S5F18 = QtGui.QCheckBox(self.S5Widget)
        self.S5F18.setGeometry(QtCore.QRect(740, 10, 16, 20))
        self.S5F18.setText(_fromUtf8(""))
        self.S5F18.setAutoExclusive(True)
        self.S5F18.setObjectName(_fromUtf8("S5F18"))
        self.S5F0 = QtGui.QCheckBox(self.S5Widget)
        self.S5F0.setGeometry(QtCore.QRect(20, 10, 21, 20))
        self.S5F0.setText(_fromUtf8(""))
        self.S5F0.setChecked(True)
        self.S5F0.setAutoExclusive(True)
        self.S5F0.setObjectName(_fromUtf8("S5F0"))
        self.S4Widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.S4Widget.setGeometry(QtCore.QRect(90, 220, 931, 41))
        self.S4Widget.setObjectName(_fromUtf8("S4Widget"))
        self.S4F9 = QtGui.QCheckBox(self.S4Widget)
        self.S4F9.setGeometry(QtCore.QRect(380, 10, 16, 20))
        self.S4F9.setText(_fromUtf8(""))
        self.S4F9.setAutoExclusive(True)
        self.S4F9.setObjectName(_fromUtf8("S4F9"))
        self.S4F21 = QtGui.QCheckBox(self.S4Widget)
        self.S4F21.setGeometry(QtCore.QRect(860, 10, 16, 20))
        self.S4F21.setText(_fromUtf8(""))
        self.S4F21.setAutoExclusive(True)
        self.S4F21.setObjectName(_fromUtf8("S4F21"))
        self.S4F16 = QtGui.QCheckBox(self.S4Widget)
        self.S4F16.setGeometry(QtCore.QRect(660, 10, 16, 20))
        self.S4F16.setText(_fromUtf8(""))
        self.S4F16.setAutoExclusive(True)
        self.S4F16.setObjectName(_fromUtf8("S4F16"))
        self.S4F11 = QtGui.QCheckBox(self.S4Widget)
        self.S4F11.setGeometry(QtCore.QRect(460, 10, 16, 20))
        self.S4F11.setText(_fromUtf8(""))
        self.S4F11.setAutoExclusive(True)
        self.S4F11.setObjectName(_fromUtf8("S4F11"))
        self.S4F6 = QtGui.QCheckBox(self.S4Widget)
        self.S4F6.setGeometry(QtCore.QRect(260, 10, 16, 20))
        self.S4F6.setText(_fromUtf8(""))
        self.S4F6.setAutoExclusive(True)
        self.S4F6.setObjectName(_fromUtf8("S4F6"))
        self.S4F18 = QtGui.QCheckBox(self.S4Widget)
        self.S4F18.setGeometry(QtCore.QRect(740, 10, 16, 20))
        self.S4F18.setText(_fromUtf8(""))
        self.S4F18.setAutoExclusive(True)
        self.S4F18.setObjectName(_fromUtf8("S4F18"))
        self.S4F7 = QtGui.QCheckBox(self.S4Widget)
        self.S4F7.setGeometry(QtCore.QRect(300, 10, 16, 20))
        self.S4F7.setText(_fromUtf8(""))
        self.S4F7.setAutoExclusive(True)
        self.S4F7.setObjectName(_fromUtf8("S4F7"))
        self.S4F4 = QtGui.QCheckBox(self.S4Widget)
        self.S4F4.setGeometry(QtCore.QRect(180, 10, 16, 20))
        self.S4F4.setText(_fromUtf8(""))
        self.S4F4.setAutoExclusive(True)
        self.S4F4.setObjectName(_fromUtf8("S4F4"))
        self.S4F17 = QtGui.QCheckBox(self.S4Widget)
        self.S4F17.setGeometry(QtCore.QRect(700, 10, 16, 20))
        self.S4F17.setText(_fromUtf8(""))
        self.S4F17.setAutoExclusive(True)
        self.S4F17.setObjectName(_fromUtf8("S4F17"))
        self.S4F15 = QtGui.QCheckBox(self.S4Widget)
        self.S4F15.setGeometry(QtCore.QRect(620, 10, 16, 20))
        self.S4F15.setText(_fromUtf8(""))
        self.S4F15.setAutoExclusive(True)
        self.S4F15.setObjectName(_fromUtf8("S4F15"))
        self.S4F19 = QtGui.QCheckBox(self.S4Widget)
        self.S4F19.setGeometry(QtCore.QRect(780, 10, 16, 20))
        self.S4F19.setText(_fromUtf8(""))
        self.S4F19.setAutoExclusive(True)
        self.S4F19.setObjectName(_fromUtf8("S4F19"))
        self.S4F20 = QtGui.QCheckBox(self.S4Widget)
        self.S4F20.setGeometry(QtCore.QRect(820, 10, 16, 20))
        self.S4F20.setText(_fromUtf8(""))
        self.S4F20.setAutoExclusive(True)
        self.S4F20.setObjectName(_fromUtf8("S4F20"))
        self.S4F13 = QtGui.QCheckBox(self.S4Widget)
        self.S4F13.setGeometry(QtCore.QRect(540, 10, 16, 20))
        self.S4F13.setText(_fromUtf8(""))
        self.S4F13.setAutoExclusive(True)
        self.S4F13.setObjectName(_fromUtf8("S4F13"))
        self.S4F10 = QtGui.QCheckBox(self.S4Widget)
        self.S4F10.setGeometry(QtCore.QRect(420, 10, 16, 20))
        self.S4F10.setText(_fromUtf8(""))
        self.S4F10.setAutoExclusive(True)
        self.S4F10.setObjectName(_fromUtf8("S4F10"))
        self.S4F3 = QtGui.QCheckBox(self.S4Widget)
        self.S4F3.setGeometry(QtCore.QRect(140, 10, 16, 20))
        self.S4F3.setText(_fromUtf8(""))
        self.S4F3.setAutoExclusive(True)
        self.S4F3.setObjectName(_fromUtf8("S4F3"))
        self.S4F14 = QtGui.QCheckBox(self.S4Widget)
        self.S4F14.setGeometry(QtCore.QRect(580, 10, 16, 20))
        self.S4F14.setText(_fromUtf8(""))
        self.S4F14.setAutoExclusive(True)
        self.S4F14.setObjectName(_fromUtf8("S4F14"))
        self.S4F22 = QtGui.QCheckBox(self.S4Widget)
        self.S4F22.setGeometry(QtCore.QRect(900, 10, 21, 20))
        self.S4F22.setText(_fromUtf8(""))
        self.S4F22.setAutoExclusive(True)
        self.S4F22.setObjectName(_fromUtf8("S4F22"))
        self.S4F8 = QtGui.QCheckBox(self.S4Widget)
        self.S4F8.setGeometry(QtCore.QRect(340, 10, 16, 20))
        self.S4F8.setText(_fromUtf8(""))
        self.S4F8.setAutoExclusive(True)
        self.S4F8.setObjectName(_fromUtf8("S4F8"))
        self.S4F5 = QtGui.QCheckBox(self.S4Widget)
        self.S4F5.setGeometry(QtCore.QRect(220, 10, 16, 20))
        self.S4F5.setText(_fromUtf8(""))
        self.S4F5.setAutoExclusive(True)
        self.S4F5.setObjectName(_fromUtf8("S4F5"))
        self.S4F2 = QtGui.QCheckBox(self.S4Widget)
        self.S4F2.setGeometry(QtCore.QRect(100, 10, 16, 20))
        self.S4F2.setText(_fromUtf8(""))
        self.S4F2.setAutoExclusive(True)
        self.S4F2.setObjectName(_fromUtf8("S4F2"))
        self.S4F12 = QtGui.QCheckBox(self.S4Widget)
        self.S4F12.setGeometry(QtCore.QRect(500, 10, 16, 20))
        self.S4F12.setText(_fromUtf8(""))
        self.S4F12.setAutoExclusive(True)
        self.S4F12.setObjectName(_fromUtf8("S4F12"))
        self.S4F1 = QtGui.QCheckBox(self.S4Widget)
        self.S4F1.setGeometry(QtCore.QRect(60, 10, 16, 20))
        self.S4F1.setText(_fromUtf8(""))
        self.S4F1.setAutoExclusive(True)
        self.S4F1.setObjectName(_fromUtf8("S4F1"))
        self.S4F0 = QtGui.QCheckBox(self.S4Widget)
        self.S4F0.setGeometry(QtCore.QRect(20, 10, 21, 20))
        self.S4F0.setText(_fromUtf8(""))
        self.S4F0.setChecked(True)
        self.S4F0.setAutoExclusive(True)
        self.S4F0.setObjectName(_fromUtf8("S4F0"))
        self.S3Widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.S3Widget.setGeometry(QtCore.QRect(90, 180, 931, 41))
        self.S3Widget.setObjectName(_fromUtf8("S3Widget"))
        self.S3F9 = QtGui.QCheckBox(self.S3Widget)
        self.S3F9.setGeometry(QtCore.QRect(380, 10, 16, 20))
        self.S3F9.setText(_fromUtf8(""))
        self.S3F9.setAutoExclusive(True)
        self.S3F9.setObjectName(_fromUtf8("S3F9"))
        self.S3F2 = QtGui.QCheckBox(self.S3Widget)
        self.S3F2.setGeometry(QtCore.QRect(100, 10, 16, 20))
        self.S3F2.setText(_fromUtf8(""))
        self.S3F2.setAutoExclusive(True)
        self.S3F2.setObjectName(_fromUtf8("S3F2"))
        self.S3F20 = QtGui.QCheckBox(self.S3Widget)
        self.S3F20.setGeometry(QtCore.QRect(820, 10, 16, 20))
        self.S3F20.setText(_fromUtf8(""))
        self.S3F20.setAutoExclusive(True)
        self.S3F20.setObjectName(_fromUtf8("S3F20"))
        self.S3F16 = QtGui.QCheckBox(self.S3Widget)
        self.S3F16.setGeometry(QtCore.QRect(660, 10, 16, 20))
        self.S3F16.setText(_fromUtf8(""))
        self.S3F16.setAutoExclusive(True)
        self.S3F16.setObjectName(_fromUtf8("S3F16"))
        self.S3F3 = QtGui.QCheckBox(self.S3Widget)
        self.S3F3.setGeometry(QtCore.QRect(140, 10, 16, 20))
        self.S3F3.setText(_fromUtf8(""))
        self.S3F3.setAutoExclusive(True)
        self.S3F3.setObjectName(_fromUtf8("S3F3"))
        self.S3F17 = QtGui.QCheckBox(self.S3Widget)
        self.S3F17.setGeometry(QtCore.QRect(700, 10, 16, 20))
        self.S3F17.setText(_fromUtf8(""))
        self.S3F17.setAutoExclusive(True)
        self.S3F17.setObjectName(_fromUtf8("S3F17"))
        self.S3F12 = QtGui.QCheckBox(self.S3Widget)
        self.S3F12.setGeometry(QtCore.QRect(500, 10, 16, 20))
        self.S3F12.setText(_fromUtf8(""))
        self.S3F12.setAutoExclusive(True)
        self.S3F12.setObjectName(_fromUtf8("S3F12"))
        self.S3F11 = QtGui.QCheckBox(self.S3Widget)
        self.S3F11.setGeometry(QtCore.QRect(460, 10, 16, 20))
        self.S3F11.setText(_fromUtf8(""))
        self.S3F11.setAutoExclusive(True)
        self.S3F11.setObjectName(_fromUtf8("S3F11"))
        self.S3F1 = QtGui.QCheckBox(self.S3Widget)
        self.S3F1.setGeometry(QtCore.QRect(60, 10, 16, 20))
        self.S3F1.setText(_fromUtf8(""))
        self.S3F1.setAutoExclusive(True)
        self.S3F1.setObjectName(_fromUtf8("S3F1"))
        self.S3F10 = QtGui.QCheckBox(self.S3Widget)
        self.S3F10.setGeometry(QtCore.QRect(420, 10, 16, 20))
        self.S3F10.setText(_fromUtf8(""))
        self.S3F10.setAutoExclusive(True)
        self.S3F10.setObjectName(_fromUtf8("S3F10"))
        self.S3F8 = QtGui.QCheckBox(self.S3Widget)
        self.S3F8.setGeometry(QtCore.QRect(340, 10, 16, 20))
        self.S3F8.setText(_fromUtf8(""))
        self.S3F8.setAutoExclusive(True)
        self.S3F8.setObjectName(_fromUtf8("S3F8"))
        self.S3F22 = QtGui.QCheckBox(self.S3Widget)
        self.S3F22.setGeometry(QtCore.QRect(900, 10, 21, 20))
        self.S3F22.setText(_fromUtf8(""))
        self.S3F22.setAutoExclusive(True)
        self.S3F22.setObjectName(_fromUtf8("S3F22"))
        self.S3F15 = QtGui.QCheckBox(self.S3Widget)
        self.S3F15.setGeometry(QtCore.QRect(620, 10, 16, 20))
        self.S3F15.setText(_fromUtf8(""))
        self.S3F15.setAutoExclusive(True)
        self.S3F15.setObjectName(_fromUtf8("S3F15"))
        self.S3F14 = QtGui.QCheckBox(self.S3Widget)
        self.S3F14.setGeometry(QtCore.QRect(580, 10, 16, 20))
        self.S3F14.setText(_fromUtf8(""))
        self.S3F14.setAutoExclusive(True)
        self.S3F14.setObjectName(_fromUtf8("S3F14"))
        self.S3F6 = QtGui.QCheckBox(self.S3Widget)
        self.S3F6.setGeometry(QtCore.QRect(260, 10, 16, 20))
        self.S3F6.setText(_fromUtf8(""))
        self.S3F6.setAutoExclusive(True)
        self.S3F6.setObjectName(_fromUtf8("S3F6"))
        self.S3F21 = QtGui.QCheckBox(self.S3Widget)
        self.S3F21.setGeometry(QtCore.QRect(860, 10, 16, 20))
        self.S3F21.setText(_fromUtf8(""))
        self.S3F21.setAutoExclusive(True)
        self.S3F21.setObjectName(_fromUtf8("S3F21"))
        self.S3F19 = QtGui.QCheckBox(self.S3Widget)
        self.S3F19.setGeometry(QtCore.QRect(780, 10, 16, 20))
        self.S3F19.setText(_fromUtf8(""))
        self.S3F19.setAutoExclusive(True)
        self.S3F19.setObjectName(_fromUtf8("S3F19"))
        self.S3F13 = QtGui.QCheckBox(self.S3Widget)
        self.S3F13.setGeometry(QtCore.QRect(540, 10, 16, 20))
        self.S3F13.setText(_fromUtf8(""))
        self.S3F13.setAutoExclusive(True)
        self.S3F13.setObjectName(_fromUtf8("S3F13"))
        self.S3F18 = QtGui.QCheckBox(self.S3Widget)
        self.S3F18.setGeometry(QtCore.QRect(740, 10, 16, 20))
        self.S3F18.setText(_fromUtf8(""))
        self.S3F18.setAutoExclusive(True)
        self.S3F18.setObjectName(_fromUtf8("S3F18"))
        self.S3F7 = QtGui.QCheckBox(self.S3Widget)
        self.S3F7.setGeometry(QtCore.QRect(300, 10, 16, 20))
        self.S3F7.setText(_fromUtf8(""))
        self.S3F7.setAutoExclusive(True)
        self.S3F7.setObjectName(_fromUtf8("S3F7"))
        self.S3F5 = QtGui.QCheckBox(self.S3Widget)
        self.S3F5.setGeometry(QtCore.QRect(220, 10, 16, 20))
        self.S3F5.setText(_fromUtf8(""))
        self.S3F5.setAutoExclusive(True)
        self.S3F5.setObjectName(_fromUtf8("S3F5"))
        self.S3F4 = QtGui.QCheckBox(self.S3Widget)
        self.S3F4.setGeometry(QtCore.QRect(180, 10, 16, 20))
        self.S3F4.setText(_fromUtf8(""))
        self.S3F4.setAutoExclusive(True)
        self.S3F4.setObjectName(_fromUtf8("S3F4"))
        self.S3F0 = QtGui.QCheckBox(self.S3Widget)
        self.S3F0.setGeometry(QtCore.QRect(20, 10, 21, 20))
        self.S3F0.setText(_fromUtf8(""))
        self.S3F0.setChecked(True)
        self.S3F0.setAutoExclusive(True)
        self.S3F0.setObjectName(_fromUtf8("S3F0"))
        self.S2Widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.S2Widget.setGeometry(QtCore.QRect(90, 140, 931, 41))
        self.S2Widget.setObjectName(_fromUtf8("S2Widget"))
        self.S2F9 = QtGui.QCheckBox(self.S2Widget)
        self.S2F9.setGeometry(QtCore.QRect(380, 10, 16, 20))
        self.S2F9.setText(_fromUtf8(""))
        self.S2F9.setAutoExclusive(True)
        self.S2F9.setObjectName(_fromUtf8("S2F9"))
        self.S2F4 = QtGui.QCheckBox(self.S2Widget)
        self.S2F4.setGeometry(QtCore.QRect(180, 10, 16, 20))
        self.S2F4.setText(_fromUtf8(""))
        self.S2F4.setAutoExclusive(True)
        self.S2F4.setObjectName(_fromUtf8("S2F4"))
        self.S2F2 = QtGui.QCheckBox(self.S2Widget)
        self.S2F2.setGeometry(QtCore.QRect(100, 10, 16, 20))
        self.S2F2.setText(_fromUtf8(""))
        self.S2F2.setAutoExclusive(True)
        self.S2F2.setObjectName(_fromUtf8("S2F2"))
        self.S2F16 = QtGui.QCheckBox(self.S2Widget)
        self.S2F16.setGeometry(QtCore.QRect(660, 10, 16, 20))
        self.S2F16.setText(_fromUtf8(""))
        self.S2F16.setAutoExclusive(True)
        self.S2F16.setObjectName(_fromUtf8("S2F16"))
        self.S2F11 = QtGui.QCheckBox(self.S2Widget)
        self.S2F11.setGeometry(QtCore.QRect(460, 10, 16, 20))
        self.S2F11.setText(_fromUtf8(""))
        self.S2F11.setAutoExclusive(True)
        self.S2F11.setObjectName(_fromUtf8("S2F11"))
        self.S2F3 = QtGui.QCheckBox(self.S2Widget)
        self.S2F3.setGeometry(QtCore.QRect(140, 10, 16, 20))
        self.S2F3.setText(_fromUtf8(""))
        self.S2F3.setAutoExclusive(True)
        self.S2F3.setObjectName(_fromUtf8("S2F3"))
        self.S2F12 = QtGui.QCheckBox(self.S2Widget)
        self.S2F12.setGeometry(QtCore.QRect(500, 10, 16, 20))
        self.S2F12.setText(_fromUtf8(""))
        self.S2F12.setAutoExclusive(True)
        self.S2F12.setObjectName(_fromUtf8("S2F12"))
        self.S2F17 = QtGui.QCheckBox(self.S2Widget)
        self.S2F17.setGeometry(QtCore.QRect(700, 10, 16, 20))
        self.S2F17.setText(_fromUtf8(""))
        self.S2F17.setAutoExclusive(True)
        self.S2F17.setObjectName(_fromUtf8("S2F17"))
        self.S2F1 = QtGui.QCheckBox(self.S2Widget)
        self.S2F1.setGeometry(QtCore.QRect(60, 10, 16, 20))
        self.S2F1.setText(_fromUtf8(""))
        self.S2F1.setAutoExclusive(True)
        self.S2F1.setObjectName(_fromUtf8("S2F1"))
        self.S2F22 = QtGui.QCheckBox(self.S2Widget)
        self.S2F22.setGeometry(QtCore.QRect(900, 10, 21, 20))
        self.S2F22.setText(_fromUtf8(""))
        self.S2F22.setAutoExclusive(True)
        self.S2F22.setObjectName(_fromUtf8("S2F22"))
        self.S2F14 = QtGui.QCheckBox(self.S2Widget)
        self.S2F14.setGeometry(QtCore.QRect(580, 10, 16, 20))
        self.S2F14.setText(_fromUtf8(""))
        self.S2F14.setAutoExclusive(True)
        self.S2F14.setObjectName(_fromUtf8("S2F14"))
        self.S2F10 = QtGui.QCheckBox(self.S2Widget)
        self.S2F10.setGeometry(QtCore.QRect(420, 10, 16, 20))
        self.S2F10.setText(_fromUtf8(""))
        self.S2F10.setAutoExclusive(True)
        self.S2F10.setObjectName(_fromUtf8("S2F10"))
        self.S2F8 = QtGui.QCheckBox(self.S2Widget)
        self.S2F8.setGeometry(QtCore.QRect(340, 10, 16, 20))
        self.S2F8.setText(_fromUtf8(""))
        self.S2F8.setAutoExclusive(True)
        self.S2F8.setObjectName(_fromUtf8("S2F8"))
        self.S2F15 = QtGui.QCheckBox(self.S2Widget)
        self.S2F15.setGeometry(QtCore.QRect(620, 10, 16, 20))
        self.S2F15.setText(_fromUtf8(""))
        self.S2F15.setAutoExclusive(True)
        self.S2F15.setObjectName(_fromUtf8("S2F15"))
        self.S2F13 = QtGui.QCheckBox(self.S2Widget)
        self.S2F13.setGeometry(QtCore.QRect(540, 10, 16, 20))
        self.S2F13.setText(_fromUtf8(""))
        self.S2F13.setAutoExclusive(True)
        self.S2F13.setObjectName(_fromUtf8("S2F13"))
        self.S2F6 = QtGui.QCheckBox(self.S2Widget)
        self.S2F6.setGeometry(QtCore.QRect(260, 10, 16, 20))
        self.S2F6.setText(_fromUtf8(""))
        self.S2F6.setAutoExclusive(True)
        self.S2F6.setObjectName(_fromUtf8("S2F6"))
        self.S2F21 = QtGui.QCheckBox(self.S2Widget)
        self.S2F21.setGeometry(QtCore.QRect(860, 10, 16, 20))
        self.S2F21.setText(_fromUtf8(""))
        self.S2F21.setAutoExclusive(True)
        self.S2F21.setObjectName(_fromUtf8("S2F21"))
        self.S2F19 = QtGui.QCheckBox(self.S2Widget)
        self.S2F19.setGeometry(QtCore.QRect(780, 10, 16, 20))
        self.S2F19.setText(_fromUtf8(""))
        self.S2F19.setAutoExclusive(True)
        self.S2F19.setObjectName(_fromUtf8("S2F19"))
        self.S2F7 = QtGui.QCheckBox(self.S2Widget)
        self.S2F7.setGeometry(QtCore.QRect(300, 10, 16, 20))
        self.S2F7.setText(_fromUtf8(""))
        self.S2F7.setAutoExclusive(True)
        self.S2F7.setObjectName(_fromUtf8("S2F7"))
        self.S2F18 = QtGui.QCheckBox(self.S2Widget)
        self.S2F18.setGeometry(QtCore.QRect(740, 10, 16, 20))
        self.S2F18.setText(_fromUtf8(""))
        self.S2F18.setAutoExclusive(True)
        self.S2F18.setObjectName(_fromUtf8("S2F18"))
        self.S2F20 = QtGui.QCheckBox(self.S2Widget)
        self.S2F20.setGeometry(QtCore.QRect(820, 10, 16, 20))
        self.S2F20.setText(_fromUtf8(""))
        self.S2F20.setAutoExclusive(True)
        self.S2F20.setObjectName(_fromUtf8("S2F20"))
        self.S2F5 = QtGui.QCheckBox(self.S2Widget)
        self.S2F5.setGeometry(QtCore.QRect(220, 10, 16, 20))
        self.S2F5.setText(_fromUtf8(""))
        self.S2F5.setAutoExclusive(True)
        self.S2F5.setObjectName(_fromUtf8("S2F5"))
        self.S2F0 = QtGui.QCheckBox(self.S2Widget)
        self.S2F0.setGeometry(QtCore.QRect(20, 10, 21, 20))
        self.S2F0.setText(_fromUtf8(""))
        self.S2F0.setChecked(True)
        self.S2F0.setAutoExclusive(True)
        self.S2F0.setObjectName(_fromUtf8("S2F0"))
        self.S1Widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.S1Widget.setGeometry(QtCore.QRect(90, 100, 931, 41))
        self.S1Widget.setObjectName(_fromUtf8("S1Widget"))
        self.S1F22 = QtGui.QCheckBox(self.S1Widget)
        self.S1F22.setGeometry(QtCore.QRect(900, 10, 21, 20))
        self.S1F22.setText(_fromUtf8(""))
        self.S1F22.setAutoExclusive(True)
        self.S1F22.setObjectName(_fromUtf8("S1F22"))
        self.S1F6 = QtGui.QCheckBox(self.S1Widget)
        self.S1F6.setGeometry(QtCore.QRect(260, 10, 16, 20))
        self.S1F6.setText(_fromUtf8(""))
        self.S1F6.setAutoExclusive(True)
        self.S1F6.setObjectName(_fromUtf8("S1F6"))
        self.S1F12 = QtGui.QCheckBox(self.S1Widget)
        self.S1F12.setGeometry(QtCore.QRect(500, 10, 16, 20))
        self.S1F12.setText(_fromUtf8(""))
        self.S1F12.setAutoExclusive(True)
        self.S1F12.setObjectName(_fromUtf8("S1F12"))
        self.S1F18 = QtGui.QCheckBox(self.S1Widget)
        self.S1F18.setGeometry(QtCore.QRect(740, 10, 16, 20))
        self.S1F18.setText(_fromUtf8(""))
        self.S1F18.setAutoExclusive(True)
        self.S1F18.setObjectName(_fromUtf8("S1F18"))
        self.S1F2 = QtGui.QCheckBox(self.S1Widget)
        self.S1F2.setGeometry(QtCore.QRect(100, 10, 16, 20))
        self.S1F2.setText(_fromUtf8(""))
        self.S1F2.setAutoExclusive(True)
        self.S1F2.setObjectName(_fromUtf8("S1F2"))
        self.S1F7 = QtGui.QCheckBox(self.S1Widget)
        self.S1F7.setGeometry(QtCore.QRect(300, 10, 16, 20))
        self.S1F7.setText(_fromUtf8(""))
        self.S1F7.setAutoExclusive(True)
        self.S1F7.setObjectName(_fromUtf8("S1F7"))
        self.S1F13 = QtGui.QCheckBox(self.S1Widget)
        self.S1F13.setGeometry(QtCore.QRect(540, 10, 16, 20))
        self.S1F13.setText(_fromUtf8(""))
        self.S1F13.setAutoExclusive(True)
        self.S1F13.setObjectName(_fromUtf8("S1F13"))
        self.S1F19 = QtGui.QCheckBox(self.S1Widget)
        self.S1F19.setGeometry(QtCore.QRect(780, 10, 16, 20))
        self.S1F19.setText(_fromUtf8(""))
        self.S1F19.setAutoExclusive(True)
        self.S1F19.setObjectName(_fromUtf8("S1F19"))
        self.S1F8 = QtGui.QCheckBox(self.S1Widget)
        self.S1F8.setGeometry(QtCore.QRect(340, 10, 16, 20))
        self.S1F8.setText(_fromUtf8(""))
        self.S1F8.setAutoExclusive(True)
        self.S1F8.setObjectName(_fromUtf8("S1F8"))
        self.S1F3 = QtGui.QCheckBox(self.S1Widget)
        self.S1F3.setGeometry(QtCore.QRect(140, 10, 16, 20))
        self.S1F3.setText(_fromUtf8(""))
        self.S1F3.setAutoExclusive(True)
        self.S1F3.setObjectName(_fromUtf8("S1F3"))
        self.S1F9 = QtGui.QCheckBox(self.S1Widget)
        self.S1F9.setGeometry(QtCore.QRect(380, 10, 16, 20))
        self.S1F9.setText(_fromUtf8(""))
        self.S1F9.setAutoExclusive(True)
        self.S1F9.setObjectName(_fromUtf8("S1F9"))
        self.S1F1 = QtGui.QCheckBox(self.S1Widget)
        self.S1F1.setGeometry(QtCore.QRect(60, 10, 16, 20))
        self.S1F1.setText(_fromUtf8(""))
        self.S1F1.setAutoExclusive(True)
        self.S1F1.setObjectName(_fromUtf8("S1F1"))
        self.S1F14 = QtGui.QCheckBox(self.S1Widget)
        self.S1F14.setGeometry(QtCore.QRect(580, 10, 16, 20))
        self.S1F14.setText(_fromUtf8(""))
        self.S1F14.setAutoExclusive(True)
        self.S1F14.setObjectName(_fromUtf8("S1F14"))
        self.S1F20 = QtGui.QCheckBox(self.S1Widget)
        self.S1F20.setGeometry(QtCore.QRect(820, 10, 16, 20))
        self.S1F20.setText(_fromUtf8(""))
        self.S1F20.setAutoExclusive(True)
        self.S1F20.setObjectName(_fromUtf8("S1F20"))
        self.S1F4 = QtGui.QCheckBox(self.S1Widget)
        self.S1F4.setGeometry(QtCore.QRect(180, 10, 16, 20))
        self.S1F4.setText(_fromUtf8(""))
        self.S1F4.setAutoExclusive(True)
        self.S1F4.setObjectName(_fromUtf8("S1F4"))
        self.S1F10 = QtGui.QCheckBox(self.S1Widget)
        self.S1F10.setGeometry(QtCore.QRect(420, 10, 16, 20))
        self.S1F10.setText(_fromUtf8(""))
        self.S1F10.setAutoExclusive(True)
        self.S1F10.setObjectName(_fromUtf8("S1F10"))
        self.S1F15 = QtGui.QCheckBox(self.S1Widget)
        self.S1F15.setGeometry(QtCore.QRect(620, 10, 16, 20))
        self.S1F15.setText(_fromUtf8(""))
        self.S1F15.setAutoExclusive(True)
        self.S1F15.setObjectName(_fromUtf8("S1F15"))
        self.S1F21 = QtGui.QCheckBox(self.S1Widget)
        self.S1F21.setGeometry(QtCore.QRect(860, 10, 16, 20))
        self.S1F21.setText(_fromUtf8(""))
        self.S1F21.setAutoExclusive(True)
        self.S1F21.setObjectName(_fromUtf8("S1F21"))
        self.S1F16 = QtGui.QCheckBox(self.S1Widget)
        self.S1F16.setGeometry(QtCore.QRect(660, 10, 16, 20))
        self.S1F16.setText(_fromUtf8(""))
        self.S1F16.setAutoExclusive(True)
        self.S1F16.setObjectName(_fromUtf8("S1F16"))
        self.S1F5 = QtGui.QCheckBox(self.S1Widget)
        self.S1F5.setGeometry(QtCore.QRect(220, 10, 16, 20))
        self.S1F5.setText(_fromUtf8(""))
        self.S1F5.setAutoExclusive(True)
        self.S1F5.setObjectName(_fromUtf8("S1F5"))
        self.S1F11 = QtGui.QCheckBox(self.S1Widget)
        self.S1F11.setGeometry(QtCore.QRect(460, 10, 16, 20))
        self.S1F11.setText(_fromUtf8(""))
        self.S1F11.setAutoExclusive(True)
        self.S1F11.setObjectName(_fromUtf8("S1F11"))
        self.S1F17 = QtGui.QCheckBox(self.S1Widget)
        self.S1F17.setGeometry(QtCore.QRect(700, 10, 16, 20))
        self.S1F17.setText(_fromUtf8(""))
        self.S1F17.setAutoExclusive(True)
        self.S1F17.setObjectName(_fromUtf8("S1F17"))
        self.S1F0 = QtGui.QCheckBox(self.S1Widget)
        self.S1F0.setGeometry(QtCore.QRect(20, 10, 21, 20))
        self.S1F0.setText(_fromUtf8(""))
        self.S1F0.setChecked(True)
        self.S1F0.setAutoExclusive(True)
        self.S1F0.setObjectName(_fromUtf8("S1F0"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.lineEdit.setText(_translate("MainWindow", "   o   1   2   3   4   5    6   7    8   9  10  11 12 13 14 15 16  17 18 19 20 21 22", None))
        self.identify_chord.setText(_translate("MainWindow", "Identify Chord", None))
        self.clear_fret_selections.setText(_translate("MainWindow", "Clear Fret Selections", None))
        self.label.setText(_translate("MainWindow", "Tuning: ", None))

